const tasks = [
  {
    id: "1",
    title: "Task 1",
    status: "In Progress",
    priority: "High",
    date: "12/2/2025",
    src: "/user1.svg",
  },
  {
    id: "2",
    title: "Task 2",
    status: "Done",
    priority: "Medium",
    date: "12/5/2025",
    src: "/user2.svg",
  },
  {
    id: "3",
    title: "Task 3",
    status: "Stuck",
    priority: "Low",
    date: "12/8/2025",
    src: "/user3.svg",
  },
  {
    id: "4",
    title: "Task 4",
    status: "Not Started",
    priority: "High",
    date: "12/10/2025",
    src: "/user4.svg",
  },
  {
    id: "5",
    title: "Task 5",
    status: "In Progress",
    priority: "Medium",
    date: "12/12/2025",
    src: "/userimg.png",
  },
  {
    id: "6",
    title: "Task 6",
    status: "Done",
    priority: "High",
    date: "12/12/2025",
    src: "/userimg.png",
  },
  {
    id: "7",
    title: "Task 7",
    status: "In Progress",
    priority: "High",
    date: "12/12/2025",
    src: "/user4.svg",
  },
  {
    id: "8",
    title: "Task 8",
    status: "Stuck",
    priority: "High",
    date: "12/12/2025",
    src: "/user4.svg",
  },
  {
    id: "9",
    title: "Task 9",
    status: "Stuck",
    priority: "low",
    date: "12/12/2025",
    src: "/user4.svg",
  },
];

export default tasks;
