import localFont from "next/font/local";
import "./globals.css";
import { Inter } from 'next/font/google';



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const inter = Inter({
  subsets: ['latin'],   // Specify language subsets
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // All weights
  display: 'swap',      // Ensures visible text during load
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`
        ${inter.className}
        ${geistSans.variable} 
        ${geistMono.variable}
        `}>
        {children}
      </body>
    </html>
  );
}
